timeline_size=20

timeline_size_fullscreen=32

timeline_line_width=2
# The overall size scale for control bar buttons (default is usually 32 or 40)
controls_size=24

# The spacing/padding between the buttons in the control bar
controls_margin=6

# The padding inside the controls container itself
controls_padding=4
color_timeline_cached=33FFFFFF
color_timeline_clear=00FFFFFF

# Adjust the opacity of the main control containers 
# Format: AARRGGBB (e.g., 80000000 is 50% opacity black)
color_background=80111111
