[main]
launch-prefix=uwsm-app --
font=JetBrainsMono Nerd Font:size=12
prompt="> "
icon-theme=Papirus
icons-enabled=yes
fields=filename,name,generic,exec,keywords
show-actions=no
terminal=ghostty
lines=4
width=40
horizontal-pad=5
vertical-pad=10
inner-pad=10
image-size-ratio=1
line-height=20

# Positioning on screen
anchor=center

[colors]
# Format: RRGGBBAA (RGB + Alpha transparency)
background=073642ff
text=839496ff
prompt=93a1a1ff
placeholder=586e75ff
input=839496ff
match=cb4b16ff
selection=002b36ff
selection-text=2aa198ff
selection-match=cb4b16ff
counter=586e75ff
border=2aa198ff

[border]
width=1
radius=0

[dmenu]
mode=index              # "text" or "index
exit-immediately-if-empty=yes

[key-bindings]
cancel=Escape Control+c
execute=Return KP_Enter
prev=Up Control+p
next=Down Control+n
prev-page=Page_Up
next-page=Page_Down
delete-line-backward=Control+u
