unbind C-b
set -g prefix C-space
bind C-space send-prefix

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind g display-popup -E -w 85% -h 85% "lazygit"
bind y display-popup -E -w 85% -h 85% "yazi"
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
# Use Alt + h,j,k,l to switch panes without prefix
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# OR: Use Prefix + h,j,k,l (if you prefer holding your prefix key first)
bind h resize-pane -L 5
bind j resize-pane -D 5
bind k resize-pane -U 5
bind l resize-pane -R 5
unbind '"'
unbind %
unbind r
bind X kill-window -a
bind r source-file ~/.config/tmux/tmux.conf \; display " Reloaded!"
