unbind C-b
set -g prefix C-space
bind C-space send-prefix
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
 
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"

bind X kill-session
bind-key Escape switch-client -T normal-mode \; display-message " -- NORMAL MODE -- "

bind-key -T normal-mode h select-pane -L
bind-key -T normal-mode j select-pane -D
bind-key -T normal-mode k select-pane -U
bind-key -T normal-mode l select-pane -R

# Inside Normal Mode: Resizing (No prefix needed)
bind-key -T normal-mode H resize-pane -L 5
bind-key -T normal-mode J resize-pane -D 5
bind-key -T normal-mode K resize-pane -U 5
bind-key -T normal-mode L resize-pane -R 5

# Inside Normal Mode: Window & Split management (No prefix needed)
bind-key -T normal-mode | split-window -h -c "#{pane_current_path}"
bind-key -T normal-mode - split-window -v -c "#{pane_current_path}"
bind-key -T normal-mode c new-window -c "#{pane_current_path}"
bind-key -T normal-mode X kill-session

# Press ESC again to get back to standard terminal input (Insert Mode)

bind-key -T normal-mode Escape switch-client -T root \; display-message " -- INSERT MODE -- "
