set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",*:RGB"

set -s escape-time 10
set -g history-limit 50000
set -g status-interval 10
set -g focus-events on

set -s set-clipboard on
set -g base-index 1
set -g pane-base-index 1
set-option -g detach-on-destroy off
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set-window-option -g mode-keys vi
