set -g status-position bottom
set -g status "on"
set -g status-style "fg=#888888,bg=#000000"
set -g mode-style "fg=#000000,bg=#ffffff,bold"
set -g message-style "fg=#ffffff,bg=#0f0f0f,bold"
set -g message-command-style "fg=#ffffff,bg=#0d0d0d,bold"
set -g pane-border-style "fg=#111111"
set -g pane-active-border-style "fg=#ffffff"
set -g status-justify "left" 
set -g status-left-length "60"
set -g status-right-length "60"
os="#( \
  if [ \"$(uname)\" = 'Darwin' ]; then echo '󰀵'; \
  elif [ \"$(uname)\" = 'FreeBSD' ]; then echo ''; \
  elif grep -qi 'arch' /etc/os-release 2>/dev/null; then echo '󰣇'; \
  elif grep -qi 'void' /etc/os-release 2>/dev/null; then echo ''; \
  elif grep -qi 'ubuntu' /etc/os-release 2>/dev/null; then echo '󰕈'; \
  elif grep -qi 'debian' /etc/os-release 2>/dev/null; then echo '󰣚'; \
  elif grep -qi -e 'suse' -e 'opensuse' /etc/os-release 2>/dev/null; then echo ''; \
  elif grep -qi 'fedora' /etc/os-release 2>/dev/null; then echo ''; \
  elif grep -qi 'nixos' /etc/os-release 2>/dev/null; then echo ''; \
  elif grep -qi 'alpine' /etc/os-release 2>/dev/null; then echo ''; \
  elif grep -qi 'gentoo' /etc/os-release 2>/dev/null; then echo ''; \
  elif grep -qi 'raspbian' /etc/os-release 2>/dev/null; then echo ''; \
  elif grep -qi 'rocky' /etc/os-release 2>/dev/null; then echo ''; \
  elif grep -qi 'almalinux' /etc/os-release 2>/dev/null; then echo ''; \
  elif grep -qi 'centos' /etc/os-release 2>/dev/null; then echo ''; \
  elif grep -qi 'kali' /etc/os-release 2>/dev/null; then echo ''; \
  elif grep -qi 'mint' /etc/os-release 2>/dev/null; then echo '󰣭'; \
  elif grep -qi 'manjaro' /etc/os-release 2>/dev/null; then echo ''; \
  elif grep -qi 'microsoft' /proc/version 2>/dev/null || [ -n \"$WSL_DISTRO_NAME\" ]; then echo '󰍲'; \
  else echo ''; fi \
)"
set -g status-left "#[fg=#ffffff,bg=#0f0f0f,bold] $os #S:#I.#P #[fg=#0f0f0f,bg=#000000]"
setw -g window-status-activity-style "underscore,fg=#ffffff,bg=#000000"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#555555,bg=#000000"
# Inactive Window Tab (No Icons)
setw -g window-status-format '#[fg=#666666,bg=#000000] #I #[fg=#222222] #[fg=#666666]#{b:pane_current_path} '
# Active Window Tab (No Icons)
setw -g window-status-current-format '#[fg=#000000,bg=#1c1c1c]#[fg=#ffffff,bg=#1c1c1c,bold] #I #[fg=#333333,bg=#1c1c1c] #[fg=#ffffff,bold]#{b:pane_current_path} #[fg=#1c1c1c,bg=#000000]'
# High-contrast noticeable monochrome gradient
set -g status-right "#[fg=#1c1c1c,bg=#000000]#[fg=#141414,bg=#1c1c1c]#[fg=#0d0d0d,bg=#141414]#[fg=#ffffff,bg=#0d0d0d,bold]  #H "
