set -g status-position top
set -g status-interval 2
set -g status "on"
set -g status-style "fg=#888888,bg=#000000"
set -g mode-style "fg=#000000,bg=#ffffff,bold"
set -g message-style "fg=#ffffff,bg=#0d0d0d,bold"
set -g message-command-style "fg=#ffffff,bg=#0d0d0d,bold"
set -g pane-border-style "fg=#111111"
set -g pane-active-border-style "fg=#ffffff"
set -g status-justify "left" 
set -g status-left-length "60"
set -g status-right-length "60"
set -g status-left "#[fg=#ffffff,bg=#1c1c1c,bold] 󰘳 #S:#I.#P #[fg=#1c1c1c,bg=#0d0d0d]#[fg=#888888,bg=#0d0d0d,bold]  #W #[fg=#0d0d0d,bg=#000000]"
set -g status-right "#[fg=#0d0d0d,bg=#000000]#[fg=#ffffff,bg=#0d0d0d,bold]  #H "
setw -g window-status-activity-style "underscore,fg=#ffffff,bg=#000000"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#555555,bg=#000000"
setw -g window-status-format '#[fg=#666666,bg=#000000] #I #[fg=#222222] #[fg=#666666]󰉋 #{b:pane_current_path} '
setw -g window-status-current-format '#[fg=#000000,bg=#1c1c1c]#[fg=#ffffff,bg=#1c1c1c,bold] #I #[fg=#333333,bg=#1c1c1c] #[fg=#ffffff,bold]󰝰 #{b:pane_current_path}#(cd #{pane_current_path} && git rev-parse --abbrev-ref HEAD >/dev/null 2>&1 && echo " #[fg=#333333]#[fg=#0070f3,bold]  $(git rev-parse --abbrev-ref HEAD)") #[fg=#1c1c1c,bg=#000000]'
