set -g default-command "${SHELL}"

source-file ~/.config/tmux/settings.tmux
source-file ~/.config/tmux/binds.tmux
# source-file ~/.config/tmux/solarized-osaka-light.conf
source-file ~/.config/tmux/solarized-osaka-dark.tmux
source-file ~/.config/tmux/plugins.tmux
