set -g default-command "${SHELL}"
set -g default-terminal "tmux-256color"
set -sg escape-time 0
set -g focus-events on
set -as terminal-features ",xterm-256color:RGB"
setw -g mode-keys vi
set -s set-clipboard on

source-file ~/dotfiles/.config/tmux/keybinds.conf
source-file ~/dotfiles/.config/tmux/statusline.conf

set -g popup-border-lines rounded

bind-key s display-popup -w 70% -h 60% -E "tmux list-sessions -F '#{session_name}' | fzf --reverse --header='[ Switch Session ]' | xargs tmux switch-client -t"

