local config = {}
function config.setup()
    hl.config({
        general = {
            gaps_in          = 1,
            gaps_out         = 2,
            border_size      = 1,
            col              = {
                active_border = { colors = { "rgba(806100ff)", "rgba(913610ff)" }, angle = 45 },
                inactive_border = "rgba(073642aa)",
            },
            -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
            resize_on_border = false,
            -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
            allow_tearing    = false,
            layout           = "dwindle",
        },

        decoration = {
            -- rounding         = 4,
            -- rounding_power   = 5,

            -- Change transparency of focused and unfocused windows
            active_opacity   = 1.0,
            inactive_opacity = 1.0,

            shadow           = {
                enabled      = false,
                range        = 4,
                render_power = 3,
                color        = "0xee1a1a1a",
            },

            blur             = {
                enabled  = true,
                size     = 3,
                passes   = 2,
                noise    = 0.01417823,
                vibrancy = 0.1696,
            },
        },

        -- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
        dwindle = {
            smart_split = true,
            smart_resizing = true,
            preserve_split = true
        },
        -- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
        scrolling = {
            fullscreen_on_one_column = true,
            focus_fit_method = 0,
            column_width = 0.95
        },
        -- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
        master = {
            new_status = "master",
        },
        animations = {
            enabled = true,
        },
        cursor = {
            inactive_timeout = 1,
            hide_on_key_press = true
        },
        misc = {
            focus_on_activate        = true,
            force_default_wallpaper  = 0,    -- Set to 0 or 1 to disable the anime mascot wallpapers
            disable_hyprland_logo    = true, -- If true disables the random hyprland logo / anime girl background. :(
            disable_splash_rendering = true, -- If true disables the random hyprland logo / anime girl background. :(
        },
        autogenerated = false
    })
    hl.curve("easeSoft", { type = "bezier", points = { { 0.18, 0.62 }, { 0.32, 1.00 } } }) -- signature Omarchy window curve
    hl.curve("easeFade", { type = "bezier", points = { { 0.28, 0.00 }, { 0.22, 1.00 } } }) -- for fades/closes
    hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
    hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
    hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
    hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
    hl.curve("easy", { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })
    hl.animation({ leaf = "global", enabled = true, speed = 4, bezier = "quick" })
    hl.animation({ leaf = "windows", enabled = true, speed = 2.6, bezier = "easeSoft" })
    hl.animation({ leaf = "windowsIn", enabled = true, speed = 2.4, bezier = "easeSoft", style = "popin 94%" })
    hl.animation({ leaf = "windowsOut", enabled = true, speed = 2.2, bezier = "easeFade", style = "popin 95%" })
    hl.animation({ leaf = "windowsMove", enabled = true, speed = 2.8, bezier = "easeSoft" })
    hl.animation({ leaf = "workspaces", enabled = true, speed = 1.1, bezier = "almostLinear", style = "fade" })
    hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.0, bezier = "almostLinear", style = "fade" })
    hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.1, bezier = "almostLinear", style = "fade" })
    hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 1.3, bezier = "almostLinear", style = "slidevert" })
    hl.animation({ leaf = "fadeIn", enabled = true, speed = 2.0, bezier = "easeSoft" })
    hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.8, bezier = "easeFade" })
    hl.animation({ leaf = "fade", enabled = true, speed = 2.2, bezier = "easeFade" })
    hl.animation({ leaf = "layers", enabled = true, speed = 2.5, bezier = "easeOutQuint" })
    hl.animation({ leaf = "layersIn", enabled = true, speed = 2.2, bezier = "easeOutQuint", style = "fade" })
    hl.animation({ leaf = "layersOut", enabled = true, speed = 1.0, bezier = "linear", style = "fade" })
    hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.2, bezier = "almostLinear" })
    hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.0, bezier = "almostLinear" })
    hl.animation({ leaf = "border", enabled = true, speed = 2.5, bezier = "easeOutQuint" })
    hl.animation({ leaf = "zoomFactor", enabled = true, speed = 4, bezier = "quick" })
end

return config
