local config = {}
function config.setup()
    hl.config({
        general = {
            gaps_in          = 3,
            gaps_out         = 3,

            border_size      = 2,

            col              = {
                active_border   = { colors = { "rgba(016b14ff)", "rgba(00ff99ee)" }, angle = 45 },
                inactive_border = "rgba(595959aa)",
            },

            -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
            resize_on_border = false,

            -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
            allow_tearing    = false,

            layout           = "dwindle",
        },

        decoration = {
            rounding         = 3,
            rounding_power   = 5,

            -- Change transparency of focused and unfocused windows
            active_opacity   = 1.0,
            inactive_opacity = 1.0,

            shadow           = {
                enabled      = false,
                range        = 4,
                render_power = 3,
                color        = 0xee1a1a1a,
            },

            blur             = {
                enabled  = true,
                size     = 4,
                passes   = 2,
                noise    = 0,
                vibrancy = 0.1696,
            },


        },

        -- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
        dwindle = {
            smart_split = true,
            preserve_split = true
        },
        -- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
        scrolling = {
            fullscreen_on_one_column = true,
            focus_fit_method = 0,
            column_width = 0.65
        },
        -- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
        master = {
            new_status = "master",
        },
        animations = {
            enabled = true,
        },
        cursor = {
            inactive_timeout = 1,
            hide_on_key_press = true
        },
        misc = {
            focus_on_activate = true,
            force_default_wallpaper  = 0,    -- Set to 0 or 1 to disable the anime mascot wallpapers
            disable_hyprland_logo    = true, -- If true disables the random hyprland logo / anime girl background. :(
            disable_splash_rendering = true, -- If true disables the random hyprland logo / anime girl background. :(
        },
        autogenerated = false
    })

    -- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
hl.curve("easeOutExpo", { type = "bezier", points = { { 0.16, 1 }, { 0.3, 1 } } })
hl.curve("easeInOutExpo", { type = "bezier", points = { { 0.87, 0 }, { 0.13, 1 } } })
hl.curve("easeOutQuad", { type = "bezier", points = { { 0.5, 1 }, { 0.89, 1 } } })
hl.curve("overshoot", { type = "bezier", points = { { 0.175, 0.885 }, { 0.32, 1.275 } } })
hl.curve("heavyOvershoot", { type = "bezier", points = { { 0.34, 1.56 }, { 0.64, 1 } } })
hl.curve("anticipate", { type = "bezier", points = { { 0.6, -0.28 }, { 0.735, 0.045 } } })
hl.curve("hyperSnappy", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1 } } })
hl.curve("smoothStep", { type = "bezier", points = { { 0.4, 0 }, { 0.2, 1 } } })
hl.curve("easeInQuad", { type = "bezier", points = { { 0.11, 0 }, { 0.5, 0 } } })
hl.curve("easeInCubic", { type = "bezier", points = { { 0.32, 0 }, { 0.67, 0 } } })
hl.curve("easeInExpo", { type = "bezier", points = { { 0.7, 0 }, { 0.84, 0 } } })
hl.curve("easeOutCirc", { type = "bezier", points = { { 0, 0.55 }, { 0.45, 1 } } })
hl.curve("easeInBack", { type = "bezier", points = { { 0.36, 0 }, { 0.66, -0.56 } } })
hl.curve("bouncy", { type = "bezier", points = { { 0.7, 1.3 }, { 0.3, 1 } } })
hl.curve("incise", { type = "bezier", points = { { 0.19, 1 }, { 0.22, 1 } } })
    -- Default springs
hl.curve("easy", { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })
hl.curve("snappy", { type = "spring", mass = 1, stiffness = 120, dampening = 18 })
hl.curve("fluid", { type = "spring", mass = 1, stiffness = 80, dampening = 22 })
hl.curve("bouncy", { type = "spring", mass = 1, stiffness = 100, dampening = 12 })
hl.curve("heavyBounce", { type = "spring", mass = 1.4, stiffness = 90, dampening = 10 })
hl.curve("stiff", { type = "spring", mass = 0.8, stiffness = 180, dampening = 26 })
hl.curve("loose", { type = "spring", mass = 1.2, stiffness = 50, dampening = 14 })
hl.curve("instant", { type = "spring", mass = 0.501, stiffness = 220, dampening = 28 })
hl.curve("lazy", { type = "spring", mass = 1.5, stiffness = 40, dampening = 18 })
hl.curve("butter", { type = "spring", mass = 1, stiffness = 95, dampening = 24 })
hl.animation({ leaf = "global", enabled = true, speed = 6.5, spring = "snappy" })
hl.animation({ leaf = "border", enabled = true, speed = 7.0, bezier = "easeOutCirc" })
hl.animation({ leaf = "windows", enabled = true, speed = 6.0, spring = "snappy" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 5.8, spring = "lazy", bezier = "overshoot", style = "popin 92%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 5.5, bezier = "easeOutExpo", style = "popin 95%" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 6.2, spring = "snappy" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 4.5, bezier = "easeOutQuad" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 4.0, bezier = "easeOutQuad" })
hl.animation({ leaf = "fade", enabled = true, speed = 4.5, bezier = "smoothStep" })
hl.animation({ leaf = "layers", enabled = true, speed = 6.5, spring = "snappy" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 6.8, bezier = "easeOutCirc", style = "popin 95%" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 5.2, bezier = "easeOutExpo", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 4.5, bezier = "easeOutQuad" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 4.0, bezier = "easeOutQuad" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 2.5, spring = "snappy", style = "slidefade 40%" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.5, spring = "fluid", style = "slidefadvert 30%" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 3.8, bezier = "easeOutExpo", style = "slide" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7.5, bezier = "easeOutExpo" })
    ----------------
    ----  MISC  ----
    ----------------

    hl.config({
    })
end

return config
